### ISSUE TITLE
Invalid updates fail silently

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-collection2-core#19]
Related to #18, whenever an invalid property is detected, it seems like it's scrubbed out of the update without any error (even when logging out the `error` callback). It'd be great to get more visibility into what's actually going on when something goes wrong.

**Comment by aldeed** [comment]
@SachaG Yeah, the idea was to have `filter` be `true` by default because if there are extra props in your object, maybe collected from a larger form or something, then it doesn't bother the user with errors about those. They just get stripped out and then the insert or update succeeds.

This can confuse people or can sometimes hide issues with your schema, so I might contemplate having filtering off by default.

But you seem to be saying that the update is NOT succeeding, which would be strange if there's no error. I'd need to see a reproduction of that.

**Comment by SachaG** [comment]
To be honest I'm not sure if the update was succeeding or not at this point, sorry… I'll close this for now.
