### ISSUE TITLE
Unique constraint throwing Internal Server Error instead of parsed context error.

### ISSUE THREAD

**Issue by boulaycote** [aldeed/meteor-collection2-core#2]
I have set a `unique` constraint on a field, when mongo validation fails, instead of having a wrapped error message I get an **Internal Server Error**.

I have found that on line [370](https://github.com/aldeed/meteor-collection2-core/blob/master/lib/collection2.js#L370) a check is made for error code `11001`. But in my case, the error code is `11000` hence the parsing error.

I am using meteor release `1.2.1`.

**Comment by boulaycote** [comment]
Here is the actual error message

```
MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.devices.$c2_uuid  dup key: { : "1" }
```

**Comment by tahaykNSM** [comment]
I found the same problem, 
I think `unique` can only be used with index.
But I still looking

**Comment by ArThoX** [comment]
@aldeed Sorry to quote you here.

https://github.com/aldeed/meteor-collection2-core/blob/master/lib/collection2.js#L488

Is ther any reason to check for 'c2' ?

**Comment by maxpdx** [comment]
I also have this issue, any updates?

**Comment by aldeed** [comment]
@maxpdx Do you have the latest `aldeed:collection2-core` package? I thought changes were made awhile ago that would have resolved this.

Also look at the index name in mongo and make sure it starts with `c2_` because indexes created outside of collection2 can't get mapped to the correct message.

If it's still an issue, posting and linking to a small reproduction app repo is the best way to get this fixed.
