### ISSUE TITLE
Error: Field name duplication not allowed with modifiers

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-collection2-core#20]
After migrating from the Meteor package to this one, I've started getting Field name duplication not allowed with modifiers errors. I'm not really sure where they're coming from, because I don't see any duplicate field names in my modifiers… Any thoughts?

(opening this instead of https://github.com/aldeed/node-simple-schema/issues/89 because the error goes away if I disable Collection2)

**Comment by aldeed** [comment]
@SachaG To verify, you are using aldeed:collection2-core pkg directly rather than aldeed:collection2, right? And if you look at your versions file, nothing else has pulled in the Meteor `aldeed:simple-schema`?

Can you narrow down a minimal schema and insert/update call that can cause this? Generally speaking this would usually be maybe a field ending up in both `$set` and `$push` or something similar.

**Comment by SachaG** [comment]
I actually ended up removing Collection2 altogether. Since migrating to Apollo my mutations are much more centralized anyway so it probably makes more sense to do validation/etc. explicitly in my own code rather than implicitly using C2.
