### ISSUE TITLE
How do I send you money to support this?

### ISSUE THREAD

**Issue by realyze** [aldeed/meteor-collection2-core#32]
First: thanks for doing this! Second: I'd love to send you a few bucks because I'm using `collection2` on my project and I like it. How do I do this?

I've found @aldeed on gittip (or gratipay or whatever it's called now) but I find it incredibly confusing and hard to figure out how to actually support someone through that. Did you consider Patreon or donorbox or something like that?

**Comment by mattbk** [comment]
I'm with Gratipay support and can answer part of that. We switched from giving to individuals to giving to projects a few years ago, and @aldeed doesn't have any projects set up (application at https://gratipay.com/apply?). More details at http://gratipay.news. 

Sorry for the confusion.

**Comment by aldeed** [comment]
@realyze This repo has been merged back into https://github.com/aldeed/meteor-collection2 now, and there is now an OpenCollective for donations here: https://opencollective.com/meteor-collection2/

And one for SimpleSchema here: https://opencollective.com/simple-schema-js/

You (or anyone else reading this) can do one-time donation or different amount for monthly if you click the DONATE button instead of choosing Backer or Sponsor plan.
