### ISSUE TITLE
default install v1.2.0 and not v2...

### ISSUE THREAD

**Issue by DavOnGit** [aldeed/meteor-collection2-core#37]
Why default install v1.2.0 and not v2...?
Also i can't find tag v2... in this repo...

**Comment by holmrenser** [comment]
I can confirm this. When running ```meteor add aldeed:collection2-core@2.0.0``` I get the following message:

```
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Potentially incompatible change required to top-level dependency: aldeed:schema-index 1.0.0, was 1.1.1.
Constraints on package "aldeed:schema-index":

Potentially incompatible change required to top-level dependency: aldeed:collection2-core 2.0.1, was 1.2.0.
Constraints on package "aldeed:collection2-core":
* aldeed:collection2-core@2.0.0 <- top level

Potentially incompatible change required to top-level dependency: aldeed:schema-deny 1.0.0, was 1.1.0.
Constraints on package "aldeed:schema-deny":

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.
```

It seems weird that the thing holding back updating collection2 is schema-deny, which is tightly coupled with this package?

**Comment by aldeed** [comment]
These issues are due to the way Meteor version resolution works. Most likely you have other packages that don't support 2 and therefore Meteor won't do it. The best way is to `meteor remove` all packages that start with `aldeed`, plus any others you think might have a dependency on one of these packages. If it still installs 1.x, then remove it and remove some more likely culprit packages and keep repeating until it installs 2.0. Then you can install the schema-index, schema-deny, etc. on top of that and it will install the compatible versions of those.

See also https://github.com/aldeed/meteor-collection2#important-note-the-version-in-this-repo-is-deprecated
