### ISSUE TITLE
autoValue inconsistency between server and client

### ISSUE THREAD

**Issue by dovydaskukalis** [aldeed/meteor-collection2-core#49]
Upgrading from 2.0.1 to 2.0.4 introduces inconsistencies. 

```
Comments.schema = new SimpleSchema({
  createdAt: {
    type: Date,
    autoValue() {
      if (this.isInsert) {
        return new Date();
      }
    }
  },
  title: {
    type: String
  }
});
```

Running insert query like this:
```
Comments.insert({ title: 'Lorem ipsum' });
```
results in this document on client
```
{
  title: 'Lorem ipsum'
}
```

and this document on server
```
{
  createdAt: '2017-11-21T17:05:48.372+0000',
  title: 'Lorem ipsum'
}
```

So it seems that autoValue is not working properly on the client. I tested and the function runs fine though.

**Comment by aldeed** [comment]
@dovydaskukalis It has always been this way, or at least that was the intention. The default/auto values are run on the client only to make sure it passes validation, and then they are discarded. The real values are added on the server and should then sync back to the client. This is done so that you can trust the generated values.

There is an open feature request to add default values to the temporary client document and yet still don't send them to the server, but that is a tricky request that would involve hacking into Meteor's core packages more.

**Comment by dovydaskukalis** [comment]
Interesting... Somehow updating to 2.0.4 breaks a lot of things related to autoValue because it takes a few ms for Meteor to sync with server as client is updated first and it's missing these values.

**Comment by aldeed** [comment]
@dovydaskukalis collection2-core@2.0.2 had a fix for extra cleaning that was happening on the client, which might have been something you were unknowingly relying on. This would be a quick fix for you, everywhere you are inserting/updating on the client:

```js
SomeCollection.simpleSchema().clean(obj);
SomeCollection.insert(obj);
```

But note as I said that this isn't secure, so if your security relying on checking some property that is set automatically, anyone could get around it.
