### ISSUE TITLE
Unique index error not mapped

### ISSUE THREAD

**Issue by ArThoX** [aldeed/meteor-collection2-core#7]
Hi

I do have a schema defined as so:

```
export var mySchema= new SimpleSchema({
  code: {    type: String,    min:0,    max: 10,    index: true,    unique: true  },
  name: {    type: String,    min: 1,    index: true,    unique: true  }
});
```

If intserting duplicated values, the error that I obtain is `11000 E11000 duplicate key error index: meteor.country.$code_1  dup key: { : "C1" } [409]`

As per https://github.com/aldeed/meteor-collection2-core/blob/master/lib/collection2.js#L488, C2 is not found (C1) here and the error is not mapped.

Is that normal ? Whats the purpose of checking only C2 ?

Regards

**Comment by aldeed** [comment]
At the time of writing this package, Mongo didn't have enough information in the error message to be able to parse it and figure out which field it is for. Indexes created by c2 have that info because we use a certain naming convention. I'm pretty sure this is still true in latest mongo. Closing this since there is the linked issue for it.
